
GREAT Reference Manual Sample 
=============================
:numbered:

Market Data : Get rates, prices and closing to live moves
---------------------------------------------------------
Risk Data : Get sensitivities
-----------------------------
Risk views and transformation: aggregation, bucketing, bond future equivalent
----------------------------------------------------------------------------
Pnl Computing
-------------
Pnl Rate
~~~~~~~~

**Name**  Pnl.DeltaRate

**Description** This measure is computed for the following RiskTypes = 
- RateRisk
- CimBasisSwapRisk
- BasisSwapRisk
- SpotRARisk
- ARGen : RatexRateRisk, BasisxRateRisk, SpotxRateRisk, RatexBasisRisk, BasisxBasisRisk, SpotxBasisRisk, RatexSpotRisk and BasisxSpotRisk

_description is supposed to display after 'Useful Context Vars' as it is a custom info..._

**Required mapping dimensions** <<X1, RiskType>>

**Useful Context Vars** ValueDate, MarketDataRefSet, DisplayCurrency

**Algorithm**

---------------------------------------------------------------------------------------------------------------
If RiskType = RateRisk, CimBasisSwapRisk, BasisSwapRisk, SpotRARisk
  PnL.DeltaRate = Sensi.DisplayCurrency * MarketData.RateMove

If Sensi.DisplayCurrency < 1 and MarketData.RateMove = NaN then PnL.DeltaRate = 0

If RiskType = RatexRateRisk, BasisxRateRisk, SpotxRateRisk, RatexBasisRisk, 
BasisxBasisRisk, SpotxBasisRisk, RatexSpotRisk and BasisxSpotRisk
  PnL.DeltaRate = ½  * sensi.DisplayCurrency * MarketData.RateMove * MarketParam.RateMove

If Sensi.DisplayCurrency < 1 and (MarketData.RateMove = NaN or MarketParam.RateMove = NaN) 
  PnL.DeltaRate = 0
---------------------------------------------------------------------------------------------------------------

**Parent Measures** sensi.DisplayCurrency, marketData.Move, marketParam.Move

**Extra info**

Stress Tests
------------
Limits
------
Dimensions register 
--------------------
Filters, row/column labels

Other
~~~~~~
[[X1]]
RiskType
^^^^^^^^
**Name** RiskType

**Values** RateRisk, CimBasisSwapRisk, BasisSwapRisk, SpotRARisk, RatexRateRisk, BasisxRateRisk, SpotxRateRisk, RatexBasisRisk, BasisxBasisRisk, SpotxBasisRisk, RatexSpotRisk, BasisxSpotRisk, ThetaRisk, ZcInflarisk, ZspreadRisk, FastValueRisk, CredersARRisk, OisCashRisk, OisCartoRisk, ExoticRisk, FxCartoRisk, IborCartoRisk, InflaxRateRisk, OfficialLiquidityRisk, RatexInflaRisk, NominalRisk, BondSensiRisk

**isJoined** No

**isEnriched** No

**Description** Type of Risk

**Values Description**
[cols="1e,1*^",frame="topbot",options="header,autowidth"]
|=====================================================
| Dimension value |Description 

|RateRisk | Rate Risk 
|CimBasisSwapRisk     |Cross Intra Maturity Swap Risk  
|BasisSwapRisk      |a  
|SpotRaRisk     |a 
|NominalRisk       |a 
|BondSensiRisk     |a 
|ZcInflaRisk        |a 
|=====================================================
**Extra Info** ARGen = crossed risks ex: BasisxRateRisk

Context Data register 
---------------------
Market Data context values
~~~~~~~~~~~~~~~~~~~~~~~~~~
Bucketing context values
~~~~~~~~~~~~~~~~~~~~~~~~
Other
~~~~
